language: elixir
matrix:
  include:
    - otp_release: 18.2.1
      elixir: 1.2.5
      script: mix test
    - otp_release: 18.3
      elixir: 1.3.2
      script: mix test
    - otp_release: 19.0
      elixir: 1.3.2
      script: mix test
    - otp_release: 18.3
      elixir: 1.4.2
    - otp_release: 19.0
      elixir: 1.4.2
      script: mix test
sudo: false
services:
  - redis-server
before_script:
  - redis-cli info
